name: lint-source-code

on:
  pull_request:
    types: [synchronize]

jobs:
  css-linting:
    if: ${{ github.event.label.name != 'no-linting' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest
        uses: actions/checkout@v2
      - name: Lint files
        run: npm run lint:css