name: lint-source-code

on:
  pull_request:
    types:
      - labeled

jobs:
  css-linting:
    if: ${{ github.event.label.name == 'css-changes' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Lint files
        run: npm run lint:css