name: Lint-source-code

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Lint files
        run: npm run lint