name: version-bump

on:
  workflow_dispatch:
    inputs:
      ReleaseType:
        description: 'Release Type'
        required: true
        default: 'patch'
        type: choice
        options:
        - major
        - minor
        - patch

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest
        uses: actions/checkout@v2
      - name: setup git config
        run: |
          git config user.name "Version Bot"
          git config user.email "<>"
      - name: npm version ${ReleaseType}
        run: npm version $RELEASE_TYPE
        env:
          RELEASE_TYPE: ${{ inputs.ReleaseType }}
      - name: Push tags
        run: git push --follow-tags